$ANSIBLE_VAULT;1.1;AES256
39383666323236383030633232326533616138323034316566626161613261326465356639353830
6138616437626366613838396639656133366661356334330a613039336234343166303839393536
33363364643963353333356331616431643062623064666338303835313136646336623464313938
3437353363366132310a393766333537623365643033343165653664383162386261333830633334
36636166643637306539663932613466386233323338356239633233323734326530653935626439
35336131396130663263323664303633333030373263363036356336613461376239346139636332
386564313935663662626162666136613539
